name: Using GitHub secrets and variables

on:
    workflow_dispatch:

jobs:
    staging:
        runs-on: ubuntu-24.04
        environment: staging
        env:
            EXAMPLE_ENVIRONMENT_SECRET": ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
            EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}
        steps:
            - name: Step 1
              run: |
                echo "EXAMPLE_ENVIRONMENT_SECRET:   $EXAMPLE_ENVIRONMENT_SECRET"
                echo "EXAMPLE_ENVIRONMENT_VARIABLE: $EXAMPLE_ENVIRONMENT_VARIABLE"
    production:
        runs-on: ubuntu-24.04
        environment: production
        env:
            EXAMPLE_ENVIRONMENT_SECRET": ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
            EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}
        steps:
            - name: Step 1
              run: |
                echo "EXAMPLE_ENVIRONMENT_SECRET:   $EXAMPLE_ENVIRONMENT_SECRET"
                echo "EXAMPLE_ENVIRONMENT_VARIABLE: $EXAMPLE_ENVIRONMENT_VARIABLE"

